import React from "react";
import { EditIcon } from "../../Composants/EditIcon";
import { DeleteIcon } from "../../Composants/DeleteIcon";
import { Tooltip } from "@nextui-org/react";

///uid changer selon les donées venant du base de donnée 
export const columns = [
  {name: "NOM", uid: "nom"},
  {name: "PRENOMS", uid: "prenom"},
  {name: "ADRESSE", uid: "adresse"},
  {name: "TELEPHONE", uid: "téléphone"},
  {name: "EMAIL", uid: "email"},
  {name: "MONTANT", uid: "Montant"},
  {name: "ACTION", uid: "action"},
];
///donnnee user venant du base de donnée
export const users = [
  {
    key: "1",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  

  },
  {
    key: "2",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "3",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "4",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "5",
    nom:"MOi",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "6",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "7",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "8",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "9",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "10",
    nom: "Tony Reichert",
    Prenom: "CEO",
    Adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "11",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "12",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "13",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "14",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "15",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "16",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "17",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "18",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "19",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
  {
    key: "20",
    nom: "Tony Reichert",
    prenom: "CEO",
    adresse: "Active",
    téléphone:"0434343",
    email:"eeeeeeeeee",
    Montant:123232323,
  },
]